package org.cat.express.wyspiaexpress.command;

import com.mojang.brigadier.CommandDispatcher;
import com.mojang.brigadier.context.CommandContext;
import com.mojang.brigadier.exceptions.CommandSyntaxException;
import dev.doctor4t.wathe.api.Role;
import dev.doctor4t.wathe.cca.GameWorldComponent;
import dev.doctor4t.wathe.client.gui.RoleAnnouncementTexts;
import dev.doctor4t.wathe.util.AnnounceWelcomePayload;
import net.fabricmc.fabric.api.networking.v1.ServerPlayNetworking;
import net.minecraft.command.CommandRegistryAccess;
import net.minecraft.command.argument.EntityArgumentType;
import net.minecraft.entity.effect.StatusEffects;
import net.minecraft.server.command.CommandManager;
import net.minecraft.server.command.ServerCommandSource;
import net.minecraft.server.network.ServerPlayerEntity;
import net.minecraft.text.HoverEvent;
import net.minecraft.text.MutableText;
import net.minecraft.text.Text;
import org.agmas.harpymodloader.Harpymodloader;
import org.agmas.harpymodloader.commands.argument.RoleArgumentType;
import org.agmas.harpymodloader.events.ModdedRoleAssigned;
import org.cat.express.wyspiaexpress.WyspiaExpressCommands;
import org.cat.express.wyspiaexpress.WyspiaExpressRoles;

public final class SetRoleCommand {
    private SetRoleCommand() {}

    public static void register(CommandDispatcher<ServerCommandSource> dispatcher,
                                CommandRegistryAccess registryAccess,
                                CommandManager.RegistrationEnvironment environment) {
        dispatcher.register(CommandManager.literal("setRole")
                .requires(WyspiaExpressCommands::isOperator)
                .then(CommandManager.argument("player", EntityArgumentType.player())
                        .then(CommandManager.argument("role", RoleArgumentType.skipVanilla())
                                .executes(SetRoleCommand::execute))));
    }

    private static int execute(CommandContext<ServerCommandSource> context) throws CommandSyntaxException {
        ServerPlayerEntity targetPlayer = EntityArgumentType.getPlayer(context, "player");
        Role role = RoleArgumentType.getRole(context, "role");
        GameWorldComponent gameWorld = GameWorldComponent.KEY.get(targetPlayer.getWorld());
        final MutableText roleText = Harpymodloader.getRoleName(role).withColor(role.color()).styled(style ->
                style.withHoverEvent(new HoverEvent(HoverEvent.Action.SHOW_TEXT, Text.literal(WyspiaExpressRoles.getRoleId(role)))));

        if (!gameWorld.isRunning()) {
            context.getSource().sendFeedback(() -> Text.translatable("commands.setrole.fail"), true);
            return 0;
        }

        targetPlayer.removeStatusEffect(StatusEffects.NIGHT_VISION);

        gameWorld.addRole(targetPlayer, role);
        ModdedRoleAssigned.EVENT.invoker().assignModdedRole(targetPlayer, role);

        context.getSource().sendFeedback(() -> Text.translatable("commands.setrole.success", targetPlayer.getDisplayName(), roleText), true);

        ServerPlayNetworking.send(
                targetPlayer,
                new AnnounceWelcomePayload(
                        RoleAnnouncementTexts.ROLE_ANNOUNCEMENT_TEXTS.indexOf(Harpymodloader.autogeneratedAnnouncements.get(role)),
                        gameWorld.getAllKillerTeamPlayers().size(),
                        0
                )
        );

        return 1;
    }
}
