package org.cat.express.wyspiaexpress.packets;

import dev.doctor4t.wathe.cca.GameTimeComponent;
import dev.doctor4t.wathe.cca.GameWorldComponent;
import dev.doctor4t.wathe.client.gui.RoleAnnouncementTexts;
import dev.doctor4t.wathe.compat.TrainVoicePlugin;
import dev.doctor4t.wathe.game.GameConstants;
import dev.doctor4t.wathe.game.GameFunctions;
import dev.doctor4t.wathe.index.WatheSounds;
import dev.doctor4t.wathe.util.AnnounceWelcomePayload;
import net.fabricmc.fabric.api.networking.v1.PayloadTypeRegistry;
import net.fabricmc.fabric.api.networking.v1.ServerPlayNetworking;
import net.minecraft.item.ItemStack;
import net.minecraft.network.PacketByteBuf;
import net.minecraft.network.RegistryByteBuf;
import net.minecraft.network.codec.PacketCodec;
import net.minecraft.network.packet.CustomPayload;
import net.minecraft.server.network.ServerPlayerEntity;
import net.minecraft.util.Hand;
import net.minecraft.util.Identifier;
import org.BsXinQin.kinswathe.component.PlayerEffectComponent;
import org.agmas.harpymodloader.Harpymodloader;
import org.agmas.harpymodloader.component.WorldModifierComponent;
import org.agmas.harpymodloader.events.ModdedRoleAssigned;
import org.agmas.noellesroles.Noellesroles;
import org.cat.express.wyspiaexpress.WyspiaExpress;
import org.cat.express.wyspiaexpress.WyspiaExpressItems;
import org.cat.express.wyspiaexpress.WyspiaExpressRoles;
import org.cat.express.wyspiaexpress.components.roles.LichReviveComponent;
import org.jetbrains.annotations.NotNull;

public  record RitualDaggerC2SPacket (int target) implements CustomPayload {

    public static final Identifier RITUAL_DAGGER_PLAYLOAD_ID = Identifier.of(WyspiaExpress.MOD_ID, "ritual_dagger");
    public static final CustomPayload.Id<RitualDaggerC2SPacket> ID = new CustomPayload.Id<>(RITUAL_DAGGER_PLAYLOAD_ID);
    public static final PacketCodec<RegistryByteBuf, RitualDaggerC2SPacket> CODEC;
    public @NotNull CustomPayload.Id<? extends @NotNull CustomPayload> getId() {return ID;}

    public void write(PacketByteBuf buf) {buf.writeInt(this.target);}

    public static RitualDaggerC2SPacket read(PacketByteBuf buf) {return new RitualDaggerC2SPacket(buf.readInt());}

    public int target() {return this.target;}

    static {
        CODEC = PacketCodec.of(RitualDaggerC2SPacket::write, RitualDaggerC2SPacket::read);
    }
    public static void register(){
        PayloadTypeRegistry.playC2S().register(ID, CODEC);
        ServerPlayNetworking.registerGlobalReceiver(ID, RitualDaggerC2SPacket::handle);
    }
    public static void handle(@NotNull RitualDaggerC2SPacket payload, @NotNull ServerPlayNetworking.Context context) {
        ServerPlayerEntity player = context.player();
        context.server().execute(() -> {

            ItemStack mainHandStack = player.getMainHandStack();
            if (!mainHandStack.isOf(WyspiaExpressItems.RITUAL_DAGGER)) return;
            if (player.getItemCooldownManager().isCoolingDown(mainHandStack.getItem())) return;
            if (!(player.getServerWorld().getEntityById(payload.target()) instanceof @NotNull ServerPlayerEntity target) || target.distanceTo(player) > 3.0F) return;

            GameWorldComponent gameWorldComponent = GameWorldComponent.KEY.get(target.getWorld());

            PlayerEffectComponent playerEffectComponent = PlayerEffectComponent.KEY.get(target);

            target.playSound(WatheSounds.ITEM_KNIFE_STAB, 1.0f, 1.0f);
            WyspiaExpressItems.setItemCooldown(player, WyspiaExpressItems.RITUAL_DAGGER, null);
            playerEffectComponent.setStunTicks(WyspiaExpress.ITEMS_CONFIG.itemConfig.ritualDaggerConfig.duration());

            //  only convert if the game is actually running and they are not already cultist
            if (gameWorldComponent.isRunning() && !gameWorldComponent.isRole(target, WyspiaExpressRoles.CULTIST)) {
                gameWorldComponent.addRole(target, WyspiaExpressRoles.CULTIST);
                ServerPlayNetworking.send(
                        target,
                        new AnnounceWelcomePayload(
                                RoleAnnouncementTexts.ROLE_ANNOUNCEMENT_TEXTS.indexOf(Harpymodloader.autogeneratedAnnouncements.get(WyspiaExpressRoles.CULTIST)),
                                gameWorldComponent.getAllKillerTeamPlayers().size(),
                                0
                        )
                );
                ModdedRoleAssigned.EVENT.invoker().assignModdedRole(player, WyspiaExpressRoles.CULTIST);

                // add time if a civilian is converted
                if (gameWorldComponent.isInnocent(target)) {
                    GameTimeComponent.KEY.get(target.getWorld()).addTime(GameConstants.TIME_ON_CIVILIAN_KILL);
                }
                // add counts revive to lich in case its a killer
                if (gameWorldComponent.canUseKillerFeatures(target)) {
                    var reviveComponent = LichReviveComponent.KEY.get(target.getWorld());
                    // count killers that are still alive
                    if(target.getWorld().getPlayers().stream().filter(gameWorldComponent::canUseKillerFeatures).filter(GameFunctions::isPlayerAliveAndSurvival).count()
                            + reviveComponent.getAvailableRevives() < reviveComponent.getMaxRevives())
                        reviveComponent.incrementAvailableRevives();
                }
                WorldModifierComponent.KEY.get(player.getWorld()).getModifiers(player).remove(Noellesroles.GUESSER);
                TrainVoicePlugin.resetPlayer(target.getUuid());
            }

            player.swingHand(Hand.MAIN_HAND);

        });
    }
}
