package org.cat.express.wyspiaexpress;

import dev.doctor4t.wathe.api.Role;
import dev.doctor4t.wathe.cca.GameWorldComponent;
import dev.doctor4t.wathe.cca.MapVariablesWorldComponent;
import dev.doctor4t.wathe.cca.PlayerMoodComponent;
import dev.doctor4t.wathe.client.gui.RoleAnnouncementTexts;
import dev.doctor4t.wathe.compat.TrainVoicePlugin;
import dev.doctor4t.wathe.game.GameFunctions;
import dev.doctor4t.wathe.index.WatheEntities;
import dev.doctor4t.wathe.util.AnnounceWelcomePayload;
import net.fabricmc.fabric.api.event.lifecycle.v1.ServerTickEvents;
import net.fabricmc.fabric.api.networking.v1.ServerPlayConnectionEvents;
import net.fabricmc.fabric.api.networking.v1.ServerPlayNetworking;
import net.minecraft.entity.Entity;
import net.minecraft.entity.ItemEntity;
import net.minecraft.entity.player.PlayerEntity;
import net.minecraft.entity.player.PlayerInventory;
import net.minecraft.item.Item;
import net.minecraft.item.ItemStack;
import net.minecraft.registry.RegistryKey;
import net.minecraft.server.network.ServerPlayerEntity;
import net.minecraft.server.world.ServerWorld;
import net.minecraft.sound.SoundCategory;
import net.minecraft.sound.SoundEvents;
import net.minecraft.text.ClickEvent;
import net.minecraft.text.MutableText;
import net.minecraft.text.Style;
import net.minecraft.text.Text;
import net.minecraft.util.Formatting;
import net.minecraft.util.Identifier;
import net.minecraft.util.math.Box;
import net.minecraft.util.math.Vec3d;
import net.minecraft.world.GameMode;
import net.minecraft.world.TeleportTarget;
import net.minecraft.world.World;
import org.BsXinQin.kinswathe.component.PlayerEffectComponent;
import org.agmas.harpymodloader.Harpymodloader;
import org.agmas.harpymodloader.component.WorldModifierComponent;
import org.agmas.harpymodloader.events.ModdedRoleAssigned;
import org.agmas.noellesroles.Noellesroles;
import org.cat.express.wyspiaexpress.components.PlayerDepressedComponent;
import org.cat.express.wyspiaexpress.components.PlayerFreezeComponent;
import org.cat.express.wyspiaexpress.components.WorldComponent;
import org.cat.express.wyspiaexpress.components.roles.PlayerCultistComponent;
import org.cat.express.wyspiaexpress.config.ServerConfig;
import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;

import java.util.*;
import java.util.concurrent.ConcurrentHashMap;

public class WyspiaExpressGameFunctions {

    private static final Map<RegistryKey<World>, Boolean> prevStarting = new ConcurrentHashMap<>();
    public static void init(){
        registerEndWorldTick();
        registerOnJoin();
    }
    public static void revivedPlayer(@NotNull GameWorldComponent gameWorldComponent,@NotNull WorldComponent worldComponent,
                @NotNull ServerPlayerEntity player, @NotNull Role role, @NotNull List<Item> keptItems){

        PlayerInventory inv = player.getInventory();
        for (int i = 0; i < PlayerInventory.getHotbarSize(); i++) {
            Item item = inv.getStack(i).getItem();
            if (!keptItems.contains(item))
                player.getInventory().setStack(i, ItemStack.EMPTY);
        }

        player.changeGameMode(GameMode.ADVENTURE);
        worldComponent.removePlayerDead(player.getUuid());
        // sound effect to revived player
        player.playSoundToPlayer(SoundEvents.ENTITY_WITHER_SPAWN, SoundCategory.PLAYERS, 0.7f, 1.0f);
        // stun the revived player
        PlayerEffectComponent.KEY.get(player).setStunTicks(WyspiaExpress.ROLES_CONFIG.roleConfig.cultLeaderConfig.stun());
        // reset components
        PlayerCultistComponent.KEY.get(player).reset();
        PlayerFreezeComponent.KEY.get(player).reset();
        PlayerMoodComponent.KEY.get(player).reset();
        PlayerDepressedComponent.KEY.get(player).reset();
        WorldModifierComponent.KEY.get(player.getWorld()).getModifiers(player).remove(Noellesroles.GUESSER);
        gameWorldComponent.addRole(player, role);
        ModdedRoleAssigned.EVENT.invoker().assignModdedRole(player, role);
        ServerPlayNetworking.send(
                player,
                new AnnounceWelcomePayload(
                        RoleAnnouncementTexts.ROLE_ANNOUNCEMENT_TEXTS.indexOf(Harpymodloader.autogeneratedAnnouncements.get(role)),
                        gameWorldComponent.getAllKillerTeamPlayers().size(),
                        0
                )
        );
        TrainVoicePlugin.resetPlayer(player.getUuid());
    }
    public static void sendPlayerDeathMessage(@NotNull ServerWorld world, @NotNull GameWorldComponent gameWorldComponent,
                                              @NotNull PlayerEntity victim, @Nullable PlayerEntity killer, @Nullable Identifier deathReason) {

        Text victimName = ((MutableText) Objects.requireNonNull(victim.getDisplayName())).setStyle(Style.EMPTY.withItalic(true));
        Text killerName = killer != null ? ((MutableText) Objects.requireNonNull(killer.getDisplayName())).setStyle(Style.EMPTY.withItalic(true)) : null;
        Text reason = deathReason != null ? getDeathReason(deathReason).setStyle(Style.EMPTY.withItalic(true)) : Text.literal("Unknown reason");
        Text victimRole = Text.literal(WyspiaExpressRoles.getRoleString(gameWorldComponent.getRole(victim))).setStyle(Style.EMPTY.withItalic(true));
        Text killerRole = killer != null ? Text.literal(WyspiaExpressRoles.getRoleString(gameWorldComponent.getRole(killer))).setStyle(Style.EMPTY.withItalic(true)) : null;
        MutableText message = Text.literal("You have fallen to ").append(reason);
        if(killerName != null)
            message.append(" by ").append(killerName).append(" [").append(killerRole).append("]");
        message.setStyle(Style.EMPTY.withColor(Formatting.RED)).append("\n");

        if (gameHasAliveRole(world, gameWorldComponent, WyspiaExpressRoles.EDDIE_WAFFLES)) {
            message.append(Text.literal("Eddie Waffles awaits your guidance").setStyle(Style.EMPTY.withColor(Formatting.WHITE))).
                    append(
                            Text.literal("[click here to join him]\n")
                                    .setStyle(Style.EMPTY
                                            .withColor(Formatting.AQUA)
                                            .withClickEvent(new ClickEvent(ClickEvent.Action.RUN_COMMAND, "/sv join 5"))
                                            .withItalic(true)
                                    )
                    );
        }
        if(gameHasAliveRole(world, gameWorldComponent, WyspiaExpressRoles.LICH) && !gameWorldComponent.isRole(victim, WyspiaExpressRoles.LICH_GHOUL)) {
            message.append(Text.literal("There is still a Lich that could revive you\n").setStyle(Style.EMPTY.withColor(Formatting.DARK_GREEN)));
        }
        if(gameHasAliveRole(world, gameWorldComponent, WyspiaExpressRoles.CULT_LEADER) && PlayerCultistComponent.KEY.get(victim).isConverted()) {
            message.append(Text.literal("You are fortunate enough to be converted by a Cult Leader\n").setStyle(Style.EMPTY.withColor(Formatting.LIGHT_PURPLE)));
        }
        victim.sendMessage(message, false);

        MutableText deathMessage = Text.literal("").append(victimName)
            .append(" [").append(victimRole).append("] has died to ").append(reason);
        if(killerName != null)
            deathMessage.append(" by ").append(killerName).append(" [").append(killerRole).append("]");
        deathMessage.append("\n").setStyle(Style.EMPTY.withColor(Formatting.WHITE));
        sendMessagePlayers(world, deathMessage, victim);
    }
    public static void sendRevivedMessage(@NotNull ServerWorld world, @NotNull GameWorldComponent gameWorldComponent,
                                          @NotNull PlayerEntity player, @NotNull PlayerEntity revived){
        Text revivedName = ((MutableText) Objects.requireNonNull(revived.getDisplayName())).setStyle(Style.EMPTY.withItalic(true));
        Text playerName = ((MutableText) Objects.requireNonNull(player.getDisplayName())).setStyle(Style.EMPTY.withItalic(true));
        Text playerRole = Text.literal(WyspiaExpressRoles.getRoleString(gameWorldComponent.getRole(player))).setStyle(Style.EMPTY.withItalic(true));

        Text revivedMessage = Text.literal("").append(revivedName).append(" has been revived by ")
                .append(playerName).append(" [").append(playerRole).append("]");
        sendMessagePlayers(world, revivedMessage);
    }
    public static void sendConvertedMessage(@NotNull ServerWorld world, @NotNull GameWorldComponent gameWorldComponent,
                                     @NotNull PlayerEntity player, @NotNull PlayerEntity converted) {
        Text convertedName = ((MutableText) Objects.requireNonNull(converted.getDisplayName())).setStyle(Style.EMPTY.withItalic(true));
        Text playerName = ((MutableText) Objects.requireNonNull(player.getDisplayName())).setStyle(Style.EMPTY.withItalic(true));

        Text convertedMessage = Text.literal("").append(convertedName).append(" has been forcefully converted by ")
                .append(playerName).append("");
        sendMessagePlayers(world, convertedMessage);
    }
    public static boolean gameHasAliveRole(@NotNull ServerWorld world,@NotNull GameWorldComponent component,@NotNull Role role) {
        for(ServerPlayerEntity player : world.getPlayers()){
            if(GameFunctions.isPlayerSpectatingOrCreative(player))
                continue;
            if(component.isRole(player, role))
                return true;
        }
        return false;
    }
    public static MutableText getDeathReason(@NotNull Identifier reason){
        return Text.translatable("death_reason." + reason.toTranslationKey());
    }
    public static boolean gameHasAliveRole(@NotNull ServerWorld world,@NotNull GameWorldComponent component, @NotNull List<Role> roles) {
        for(ServerPlayerEntity player : world.getPlayers()){
            if(GameFunctions.isPlayerSpectatingOrCreative(player))
                continue;
            Role playerRole = component.getRole(player);
            if(roles.contains(playerRole))
                return true;
        }
        return false;
    }
    public static void sendMessagePlayers(@NotNull ServerWorld world, @NotNull Text message) {
        sendMessagePlayers(world, message, (PlayerEntity) null);
    }
    public static void sendMessagePlayers(@NotNull ServerWorld world, @NotNull Text message, @Nullable PlayerEntity excluded) {
        for(ServerPlayerEntity player: world.getPlayers()){
            if(player == excluded){
                continue;
            }
            player.sendMessage(message, false);
        }
    }
    public static void sendMessagePlayers(@NotNull ServerWorld world, @NotNull Text message, @NotNull List<PlayerEntity> excluded) {
        for(ServerPlayerEntity player: world.getPlayers()){
            if(excluded.contains(player)){
                continue;
            }
            player.sendMessage(message, false);
        }
    }
    private static void registerOnJoin(){
        ServerPlayConnectionEvents.JOIN.register((handler, sender, server) -> {
            ServerPlayerEntity joining = handler.player;
            server.execute(() -> {
                ServerWorld overworld = server.getOverworld();
                GameWorldComponent gwc = GameWorldComponent.KEY.get(overworld);
                WorldComponent wc = WorldComponent.KEY.get(overworld);
                if (gwc.isRunning() && wc.isPlayerDead(joining.getUuid())) {
                    joining.changeGameMode(GameMode.SPECTATOR);
                }
                else if(joining.hasPermissionLevel(2) && !gwc.isRunning()){ // op join in creative mode
                    joining.changeGameMode(GameMode.CREATIVE);
                }
                else{
                    joining.changeGameMode(GameMode.ADVENTURE);
                }
            });
        });
    }
    private static void registerEndWorldTick(){
        ServerTickEvents.END_WORLD_TICK.register(world -> {
            if (!(world instanceof ServerWorld serverWorld)) return;
            GameWorldComponent gwc = GameWorldComponent.KEY.get(world);
            GameWorldComponent.GameStatus status = gwc.getGameStatus();
            boolean gameRunning = status == GameWorldComponent.GameStatus.ACTIVE
                    || status == GameWorldComponent.GameStatus.STARTING
                    || status == GameWorldComponent.GameStatus.STOPPING;
            boolean isStarting = status == GameWorldComponent.GameStatus.STARTING;
            boolean wasStarting = prevStarting.getOrDefault(world.getRegistryKey(), false);
            if (isStarting && !wasStarting) {

                performRtp(serverWorld);
            }
            prevStarting.put(world.getRegistryKey(), isStarting);

            Box readyArea = MapVariablesWorldComponent.KEY.get(world).getReadyArea();
            for (net.minecraft.entity.player.PlayerEntity player : world.getPlayers()) {
                if (!(player instanceof ServerPlayerEntity serverPlayer)) continue;
                if (gameRunning || (readyArea != null && readyArea.contains(serverPlayer.getPos()) ) ) {
                    removeTeleportItem(serverPlayer);
                } else {
                    giveTeleportItem(serverPlayer);

                }
            }
            if (status == GameWorldComponent.GameStatus.ACTIVE && WyspiaExpress.SERVER_CONFIG.enableItemBoundChecking())
                itemBoundsCheck(serverWorld);

        });
    }

    private static void performRtp(ServerWorld world) {
        if(!WyspiaExpress.SERVER_CONFIG.enableRandomStartTp())
            return;
        List<ServerConfig.TpTargetPosition> slots = new ArrayList<>();
        for (String entry : WyspiaExpress.SERVER_CONFIG.randomStartTp()) {
            String[] parts = entry.split(",");
            if (parts.length >= 5) {
                try {
                    slots.add(new ServerConfig.TpTargetPosition(
                            Double.parseDouble(parts[0].trim()),
                            Double.parseDouble(parts[1].trim()),
                            Double.parseDouble(parts[2].trim()),
                            Float.parseFloat(parts[3].trim()),
                            Float.parseFloat(parts[4].trim())
                    ));
                } catch (NumberFormatException e) {
                }
            }
        }
        if (slots.isEmpty()) return;

        List<ServerPlayerEntity> eligiblePlayers = new ArrayList<>();
        MapVariablesWorldComponent mvc = MapVariablesWorldComponent.KEY.get(world);

        Box readyArea = mvc.getReadyArea();
        for (net.minecraft.entity.player.PlayerEntity player : world.getPlayers()) {
            if (!(player instanceof ServerPlayerEntity sp) || ! readyArea.contains(sp.getPos())) continue;
            eligiblePlayers.add(sp);
        }
        if (eligiblePlayers.isEmpty()) return;
        Collections.shuffle(eligiblePlayers);
        Collections.shuffle(slots);
        int count = Math.min(eligiblePlayers.size(), slots.size());
        for (int i = 0; i < count; i++) {
            ServerPlayerEntity player = eligiblePlayers.get(i);
            ServerConfig.TpTargetPosition slot = slots.get(i);
            TeleportTarget target = new TeleportTarget(world, new Vec3d(slot.x, slot.y, slot.z), Vec3d.ZERO, slot.yaw, slot.pitch, TeleportTarget.NO_OP);
            player.teleportTo(target);
        }
    }

    private static void giveTeleportItem(ServerPlayerEntity player) {
        boolean haveItem = false;
        for (int item = 0; item < player.getInventory().size(); item++) {
            if (player.getInventory().getStack(item).isOf(WyspiaExpressItems.TP_READY)) {
                haveItem = true;
                break;
            }
        }
        if (!haveItem) {
            player.getInventory().insertStack(WyspiaExpressItems.TP_READY.getDefaultStack());
        }
    }
    private static void removeTeleportItem(ServerPlayerEntity player) {
        for (int item = 0; item < player.getInventory().size(); item++) {
            if (player.getInventory().getStack(item).isOf(WyspiaExpressItems.TP_READY)) {
                player.getInventory().setStack(item, ItemStack.EMPTY);
            }
        }
    }
    private static void itemBoundsCheck(ServerWorld world) {
        Box playArea = MapVariablesWorldComponent.KEY.get(world).getPlayArea();
        if (playArea == null) return;
        List<Entity> targets = new ArrayList<>();
        for (PlayerEntity p : world.getPlayers()) {
            if (p instanceof ServerPlayerEntity player
                    && player.isAlive()
                    && !player.isSpectator()
                    && !player.isCreative()) {
                targets.add(player);
            }
        }
        targets.addAll(world.getEntitiesByType(WatheEntities.PLAYER_BODY, body -> true));

        if (targets.isEmpty()) return;

        for (ItemEntity item : world.getEntitiesByType(net.minecraft.entity.EntityType.ITEM, item -> !playArea.contains(item.getPos()))) {
            Entity closest = findClosestEntity(item.getPos(), targets);
            if (closest == null) continue;
            Vec3d dest = closest.getPos();
            item.requestTeleport(dest.x, dest.y, dest.z);
        }

    }
    private static Entity findClosestEntity(Vec3d from, List<Entity> candidates) {
        Entity best = null;
        double bestDist = Double.MAX_VALUE;
        for (Entity candidate : candidates) {
            double dist = from.squaredDistanceTo(candidate.getPos());
            if (dist < bestDist) {
                bestDist = dist;
                best = candidate;
            }
        }
        return best;
    }
}
